name: CI
on:
  pull_request:
  push:
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - java: 8
          - java: 11
          - java: 14
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Scala
      uses: olafurpg/setup-scala@v10
      with:
        java-version: "adopt@1.${{ matrix.java }}"
    - name: Scalafmt Model 
      run: |
        cd model
        sbt -v scalafmtCheckAll
    - name: Scalafmt Framework 
      run: |
        cd framework
        sbt -v scalafmtCheckAll
    - name: Build and Test Model
      run: |
        cd model
        sbt -v -Dfile.encoding=UTF-8 +test
        sbt publishLocal
    - name: Build and Test Framework
      run: |
        cd framework
        sbt -v -Dfile.encoding=UTF-8 +test
